name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Мы временно убираем старый кэш, чтобы сбросить битые скачанные пакеты
    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev python3-pip cmake g++
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK with Buildozer
      run: |
        # Подписываем лицензии в системном SDK
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Экспортируем жесткие пути к системному SDK и NDK для Buildozer
        export BUILDOZER_ANDROID_SDK_DIR="$ANDROID_HOME"
        export BUILDOZER_ANDROID_NDK_DIR="$ANDROID_NDK_LATEST_HOME"
        export APP_ALLOW_SDK_WARNINGS=1
        
        # Запускаем сборку
        buildozer android debug
        
